"""
OmicSage — CITE-seq Epitope Characterisation Report
reports/templates/cite/cite_epitope_report.py

Generated after cite_epitope step (Step 10).
Output: cite_10_epitope_report.html

Four sections mirroring the four sub-analyses:
  1. Run Summary
  2. Epitope Abundance Scores — heatmap of panel scores per cell type
  3. RNA-Protein Parallel Plots — side-by-side violins for matched pairs
  4. Cross-Modal Marker Table — top ADT markers + RNA counterpart + r
"""

from __future__ import annotations

import base64
import io
from datetime import datetime
from pathlib import Path
from typing import Optional

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

_DPI = 130

_CSS = """
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
           font-size: 14px; line-height: 1.6; color: #1a1a2e; background: #f7f8fc; }
    header { background: linear-gradient(135deg, #1a1a2e 0%, #16213e 60%, #0f3460 100%);
              color: white; padding: 32px 40px 24px; }
    header h1 { font-size: 1.8rem; font-weight: 700; }
    header p  { font-size: 0.85rem; opacity: 0.7; margin-top: 4px; }
    main { max-width: 1200px; margin: 0 auto; padding: 32px 24px; }
    section { background: white; border-radius: 10px;
               box-shadow: 0 1px 4px rgba(0,0,0,0.07);
               padding: 28px 32px; margin-bottom: 24px; }
    section h2 { font-size: 1.15rem; font-weight: 700; color: #0f3460;
                  border-bottom: 2px solid #e8eaf6;
                  padding-bottom: 10px; margin-bottom: 18px; }
    section h3 { font-size: 1rem; font-weight: 600; color: #16213e; margin: 16px 0 8px; }
    section p  { color: #444; margin-bottom: 12px; font-size: 0.9rem; }
    .timestamp { font-size: 0.8rem; color: #888; margin-bottom: 6px; }
    .note { font-size: 0.82rem; color: #7a5c00; background: #fffbe6;
             border-left: 3px solid #f0c040; padding: 8px 12px;
             border-radius: 4px; margin-bottom: 14px; }
    .interp { font-size: 0.82rem; color: #1e3a5f; background: #e8f0fe;
               border-left: 3px solid #4C78A8; padding: 8px 12px;
               border-radius: 4px; margin-bottom: 14px; }
    code { font-family: "SFMono-Regular", Consolas, monospace;
            background: #f0f2ff; padding: 1px 5px;
            border-radius: 3px; font-size: 0.85em; }
    .stat-grid { display: flex; flex-wrap: wrap; gap: 14px; margin-bottom: 24px; }
    .stat-card { background: #f0f2ff; border-radius: 8px; padding: 14px 20px;
                  min-width: 130px; text-align: center; flex: 1 1 130px; }
    .stat-value { font-size: 1.4rem; font-weight: 700; color: #0f3460; }
    .stat-label { font-size: 0.75rem; color: #666; margin-top: 2px; }
    table { width: 100%; border-collapse: collapse; font-size: 0.88rem; margin-top: 8px; }
    th { background: #f0f2ff; color: #0f3460; font-weight: 600;
          padding: 9px 12px; text-align: left; border-bottom: 2px solid #d0d4f0; }
    td { padding: 8px 12px; border-bottom: 1px solid #eee; vertical-align: middle; }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: #f8f9ff; }
    .fig-grid { display: flex; flex-wrap: wrap; gap: 18px; margin-top: 12px; }
    .fig-wrap { flex: 1 1 300px; max-width: 520px; }
    .fig-wrap.wide { flex: 1 1 100%; max-width: 100%; }
    .fig-wrap h3 { font-size: 0.9rem; margin-bottom: 6px; color: #16213e; }
    .fig-wrap img { width: 100%; border-radius: 6px; border: 1px solid #e8eaf6; }
    img { max-width: 100%; height: auto; }
    .r-high { color: #155724; font-weight: 600; }
    .r-low  { color: #856404; }
    .r-neg  { color: #721c24; font-weight: 600; }
    footer { text-align: center; font-size: 0.78rem; color: #aaa; padding: 24px 0 32px; }
    footer a { color: #0f3460; text-decoration: none; }
"""


def _fig_to_b64(fig) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=_DPI, bbox_inches="tight")
    plt.close(fig)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("utf-8")


def _render_page(sections: list[str], timestamp: str, dataset_name: str) -> str:
    body = "\n".join(sections)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>OmicSage -- CITE-seq Epitope Characterisation -- {dataset_name}</title>
  <style>{_CSS}</style>
</head>
<body>
  <header>
    <h1>OmicSage -- CITE-seq Epitope Characterisation</h1>
    <p>Dataset: <strong>{dataset_name}</strong> &middot; Generated {timestamp}</p>
  </header>
  <main>{body}</main>
  <footer>Generated by <a href="https://github.com/fshokor/OmicSage">OmicSage</a>
  &middot; MIT License</footer>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------

def _plot_score_heatmap(
    mdata,
    scores_df: pd.DataFrame,
    panel_used: dict,
    group_col: str,
) -> str:
    """
    Heatmap: rows = cell types, columns = epitope panels,
    values = mean epitope score per cell type.
    """
    if scores_df.empty or not panel_used:
        fig, ax = plt.subplots(figsize=(5, 2))
        ax.text(0.5, 0.5, "No epitope scores to display.",
                ha="center", va="center", transform=ax.transAxes,
                fontsize=10, color="#888")
        ax.axis("off")
        return _fig_to_b64(fig)

    adt = mdata["adt"]
    if group_col not in adt.obs.columns:
        fig, ax = plt.subplots(figsize=(5, 2))
        ax.text(0.5, 0.5, f"Group column '{group_col}' not found.",
                ha="center", va="center", transform=ax.transAxes,
                fontsize=9, color="#888")
        ax.axis("off")
        return _fig_to_b64(fig)

    panel_names = [p for p in panel_used.keys() if p in scores_df.columns]
    if not panel_names:
        fig, ax = plt.subplots(figsize=(5, 2))
        ax.text(0.5, 0.5, "Panel score columns not found in scores_df.",
                ha="center", va="center", transform=ax.transAxes,
                fontsize=9, color="#888")
        ax.axis("off")
        return _fig_to_b64(fig)

    cell_types = sorted(adt.obs[group_col].astype(str).unique())
    scores_df = scores_df.copy()
    scores_df["cell_type"] = adt.obs[group_col].astype(str).values

    matrix = np.zeros((len(cell_types), len(panel_names)))
    for i, ct in enumerate(cell_types):
        subset = scores_df[scores_df["cell_type"] == ct]
        for j, panel in enumerate(panel_names):
            matrix[i, j] = subset[panel].mean() if not subset.empty else 0.0

    fig_h = max(4, len(cell_types) * 0.5)
    fig_w = max(6, len(panel_names) * 1.2)
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))

    im = ax.imshow(matrix, aspect="auto", cmap="YlOrRd",
                   vmin=0, vmax=max(matrix.max(), 0.01))
    plt.colorbar(im, ax=ax, fraction=0.03, pad=0.02,
                 label="Mean CLR score")

    ax.set_xticks(range(len(panel_names)))
    ax.set_xticklabels(panel_names, rotation=30, ha="right", fontsize=9)
    ax.set_yticks(range(len(cell_types)))
    ax.set_yticklabels(cell_types, fontsize=9)
    ax.set_title(
        "Mean Epitope Score per Cell Type\n"
        "(CLR expression of panel proteins, averaged per cell then per group)",
        fontsize=11, fontweight="bold",
    )
    fig.tight_layout()
    return _fig_to_b64(fig)


def _plot_score_violin(
    mdata,
    scores_df: pd.DataFrame,
    panel_name: str,
    group_col: str,
) -> str:
    """
    Violin plot of one epitope panel score across all cell types.
    """
    if scores_df.empty or panel_name not in scores_df.columns:
        fig, ax = plt.subplots(figsize=(5, 2))
        ax.text(0.5, 0.5, f"No data for panel '{panel_name}'.",
                ha="center", va="center", transform=ax.transAxes,
                fontsize=9, color="#888")
        ax.axis("off")
        return _fig_to_b64(fig)

    adt = mdata["adt"]
    df = scores_df.copy()
    df["cell_type"] = adt.obs[group_col].astype(str).values

    cell_types = sorted(df["cell_type"].unique())
    data = [df[df["cell_type"] == ct][panel_name].values for ct in cell_types]
    data = [d for d in data if len(d) > 0]

    if not data:
        fig, ax = plt.subplots(figsize=(5, 2))
        ax.axis("off")
        return _fig_to_b64(fig)

    cmap = plt.get_cmap("tab10", len(cell_types))
    fig, ax = plt.subplots(figsize=(max(6, len(cell_types) * 0.9), 4))

    parts = ax.violinplot(data, positions=range(len(cell_types)),
                          showmedians=True, showextrema=False)
    for i, pc in enumerate(parts["bodies"]):
        pc.set_facecolor(cmap(i))
        pc.set_alpha(0.75)
    parts["cmedians"].set_color("#333")

    ax.set_xticks(range(len(cell_types)))
    ax.set_xticklabels(cell_types, rotation=30, ha="right", fontsize=8)
    ax.set_ylabel("Mean CLR score", fontsize=9)
    ax.set_title(f"{panel_name} Epitope Score", fontsize=10, fontweight="bold")
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    return _fig_to_b64(fig)


def _plot_rna_protein_parallel(
    mdata,
    protein: str,
    gene: str,
    r: float,
    group_col: str,
    n_top_types: int = 8,
) -> str:
    """
    Side-by-side violin: CLR expression (left) vs log-RNA (right)
    for one protein-gene pair, per cell type.
    This is the core Seurat multimodal vignette figure.
    """
    adt = mdata["adt"]
    rna = mdata["rna"]

    # Get cell type labels
    if group_col not in adt.obs.columns:
        fig, ax = plt.subplots(figsize=(4, 2))
        ax.axis("off")
        return _fig_to_b64(fig)

    labels = adt.obs[group_col].astype(str).values

    # Limit to top n_top_types by cell count for readability
    from collections import Counter
    counts = Counter(labels)
    top_types = [ct for ct, _ in counts.most_common(n_top_types)]

    # Get protein CLR vector
    prot_vec = None
    if protein in adt.var_names:
        pidx = list(adt.var_names).index(protein)
        mat = adt.layers.get("adt_clr", adt.X)
        mat = mat.toarray() if hasattr(mat, "toarray") else np.asarray(mat)
        prot_vec = mat[:, pidx].ravel()

    # Get RNA log vector
    rna_vec = None
    if gene in rna.var_names:
        gidx = list(rna.var_names).index(gene)
        rmat = rna.layers.get("logcounts", rna.X)
        rmat = rmat.toarray() if hasattr(rmat, "toarray") else np.asarray(rmat)
        rna_vec = rmat[:, gidx].ravel()

    if prot_vec is None or rna_vec is None:
        fig, ax = plt.subplots(figsize=(4, 2))
        ax.text(0.5, 0.5,
                f"'{protein}' or '{gene}' not found.",
                ha="center", va="center", transform=ax.transAxes,
                fontsize=8, color="#888")
        ax.axis("off")
        return _fig_to_b64(fig)

    mask = np.isin(labels, top_types)
    labels_f  = labels[mask]
    prot_f    = prot_vec[mask]
    rna_f     = rna_vec[mask]

    cmap = plt.get_cmap("tab10", len(top_types))
    fig, (ax_p, ax_r) = plt.subplots(1, 2, figsize=(12, 4), sharey=False)

    for ax, values, ylabel, title in [
        (ax_p, prot_f, "CLR expression",  f"{protein} (protein)"),
        (ax_r, rna_f,  "log expression",  f"{gene} (RNA)"),
    ]:
        data = [values[labels_f == ct] for ct in top_types]
        data = [d for d in data if len(d) > 0]
        if not data:
            ax.axis("off")
            continue

        parts = ax.violinplot(data, positions=range(len(top_types)),
                               showmedians=True, showextrema=False)
        for i, pc in enumerate(parts["bodies"]):
            pc.set_facecolor(cmap(i))
            pc.set_alpha(0.75)
        parts["cmedians"].set_color("#333")

        ax.set_xticks(range(len(top_types)))
        ax.set_xticklabels(top_types, rotation=30, ha="right", fontsize=8)
        ax.set_ylabel(ylabel, fontsize=9)
        ax.set_title(title, fontsize=10, fontweight="bold")
        ax.spines[["top", "right"]].set_visible(False)

    r_str = f"r = {r:.3f}" if not np.isnan(r) else "r = n/a"
    fig.suptitle(
        f"{protein} protein  ⟷  {gene} RNA  ({r_str})",
        fontsize=11, fontweight="bold",
    )
    fig.tight_layout()
    return _fig_to_b64(fig)


# ---------------------------------------------------------------------------
# HTML sections
# ---------------------------------------------------------------------------

def _section_run_summary(
    provenance: dict,
    dataset_name: str,
    timestamp: str,
) -> str:
    n_panels   = provenance.get("n_panels", 0)
    panel_names= ", ".join(provenance.get("panel_names", [])) or "none"
    preset     = provenance.get("preset") or "custom"
    has_corr   = provenance.get("has_corr_results", False)
    has_dpe    = provenance.get("has_dpe_results", False)
    groupby    = provenance.get("groupby", "?")

    cards = "".join(
        f'<div class="stat-card"><div class="stat-value">{v}</div>'
        f'<div class="stat-label">{k}</div></div>'
        for k, v in [
            ("Panels",          n_panels),
            ("Panel source",    preset),
            ("Corr results",    "✓" if has_corr else "✗"),
            ("DPE results",     "✓" if has_dpe  else "✗"),
        ]
    )
    missing = []
    if not has_corr:
        missing.append("cite_09 (protein-RNA correlation) — parallel violin plots skipped")
    if not has_dpe:
        missing.append("cite_07 (DEG/DPE) — cross-modal marker table skipped")
    missing_html = ""
    if missing:
        items = "".join(f"<li>{m}</li>" for m in missing)
        missing_html = (
            f"<p class='note'>Optional upstream results not provided — "
            f"some sub-analyses were skipped:<ul>{items}</ul></p>"
        )

    rows = "".join(
        f"<tr><td>{k}</td><td><code>{v}</code></td></tr>"
        for k, v in [
            ("Groupby",    groupby),
            ("Panels",     panel_names),
        ]
    )
    return f"""
    <section>
      <h2>Run Summary</h2>
      <p class="timestamp">Dataset: <strong>{dataset_name}</strong>
         &middot; {timestamp}</p>
      {missing_html}
      <div class="stat-grid">{cards}</div>
      <table>
        <thead><tr><th>Parameter</th><th>Value</th></tr></thead>
        <tbody>{rows}</tbody>
      </table>
    </section>"""


def _section_epitope_scores(
    mdata,
    scores_df: pd.DataFrame,
    panel_used: dict,
    group_col: str,
) -> str:
    if not panel_used or scores_df.empty:
        return """
    <section>
      <h2>Epitope Abundance Scores</h2>
      <p class="note">No panels configured — set preset or epitope_panels
      in the config.</p>
    </section>"""

    print("  Rendering epitope score heatmap ...", flush=True)
    fig_heatmap = _plot_score_heatmap(mdata, scores_df, panel_used, group_col)

    # Per-panel violin plots — one per panel
    violin_html = ""
    for panel_name in list(panel_used.keys())[:6]:  # cap at 6 for report size
        print(f"  Rendering score violin: {panel_name} ...", flush=True)
        fig_v = _plot_score_violin(mdata, scores_df, panel_name, group_col)
        violin_html += f"""
        <div class="fig-wrap">
          <h3>{panel_name}</h3>
          <img src="data:image/png;base64,{fig_v}" alt="{panel_name} score">
        </div>"""

    return f"""
    <section>
      <h2>Epitope Abundance Scores</h2>
      <p>
        Mean CLR expression of lineage-defining proteins grouped into panels.
        Scores are written to <code>obs["epitope_score_*"]</code> and can be
        used as continuous lineage markers for downstream trajectory analysis.
        Higher score = stronger expression of that lineage's surface markers.
      </p>
      <h3>Panel Score Heatmap (mean per cell type)</h3>
      <div class="fig-grid">
        <div class="fig-wrap wide">
          <img src="data:image/png;base64,{fig_heatmap}" alt="Epitope score heatmap">
        </div>
      </div>
      <h3>Per-Panel Score Distribution</h3>
      <div class="fig-grid">{violin_html}</div>
    </section>"""


def _section_rna_protein_parallel(
    mdata,
    corr_results: Optional[pd.DataFrame],
    group_col: str,
    n_pairs: int = 6,
) -> str:
    if corr_results is None or corr_results.empty:
        return """
    <section>
      <h2>RNA-Protein Parallel Plots</h2>
      <p class="note">
        Requires cite_09 correlation results.
        Re-run with cite_09 checkpoint available to enable this section.
      </p>
    </section>"""

    # Select top n_pairs by highest POSITIVE r
    # (co-regulated pairs where protein and mRNA agree — most illustrative
    # for showing what the parallel plot is designed to show).
    # Negatively correlated pairs (anti-correlated) are shown separately below.
    df = corr_results.copy()
    pairs_pos = df[df["r"] > 0].nlargest(n_pairs, "r")[["protein", "gene", "r"]].values.tolist()
    # If fewer than n_pairs positive pairs exist, fill with least-negative
    if len(pairs_pos) < n_pairs:
        pairs_neg_fill = (
            df[df["r"] <= 0]
            .nlargest(n_pairs - len(pairs_pos), "r")
            [["protein", "gene", "r"]].values.tolist()
        )
        pairs = pairs_pos + pairs_neg_fill
    else:
        pairs = pairs_pos

    pair_html = ""
    for protein, gene, r in pairs:
        print(f"  Rendering RNA-protein parallel: {protein}/{gene} ...", flush=True)
        fig_b64 = _plot_rna_protein_parallel(
            mdata, str(protein), str(gene), float(r), group_col
        )
        r_str = f"r = {float(r):.3f}"
        pair_html += f"""
        <div class="fig-wrap wide" style="margin-bottom:20px;">
          <h3>{protein} / {gene} &nbsp;<span style="font-weight:400;color:#666;font-size:0.85rem;">Spearman {r_str}</span></h3>
          <img src="data:image/png;base64,{fig_b64}"
               alt="{protein} protein vs {gene} RNA">
        </div>"""

    return f"""
    <section>
      <h2>RNA-Protein Parallel Plots</h2>
      <div class="interp">
        Each pair shows the same protein measured two ways: surface protein
        abundance (CLR, left) and mRNA expression (log-normalised, right),
        both grouped by ADT-defined cell type.
        When the shapes match — the two modalities agree.
        When they diverge — post-transcriptional regulation, differential
        secretion, or surface trafficking is at work. These are biological
        findings, not noise.
      </div>
      <p>Showing top {n_pairs} positively correlated pairs from cite_09
      (pairs where protein and mRNA are co-regulated — shapes should match).
      These are the most informative for validating RNA-protein coupling.</p>
      <div class="fig-grid">{pair_html}</div>
    </section>"""


def _section_marker_table(marker_table: pd.DataFrame) -> str:
    if marker_table.empty:
        return """
    <section>
      <h2>Cross-Modal Marker Table</h2>
      <p class="note">
        Requires cite_07 DEG/DPE results.
        Re-run with cite_07 checkpoint available to enable this section.
      </p>
    </section>"""

    def _r_cell(r_val) -> str:
        try:
            r = float(r_val)
        except (TypeError, ValueError):
            return "<td>—</td>"
        if np.isnan(r):
            return "<td>—</td>"
        css = "r-high" if r >= 0.4 else ("r-neg" if r < 0 else "r-low")
        return f"<td class='{css}'>{r:.3f}</td>"

    trows = ""
    prev_ct = None
    for _, row in marker_table.iterrows():
        ct = row["cell_type"]
        ct_cell = (
            f"<td rowspan='1' style='font-weight:600'>{ct}</td>"
            if ct != prev_ct else "<td></td>"
        )
        prev_ct = ct
        trows += (
            f"<tr>"
            f"{ct_cell}"
            f"<td><strong>{row['protein']}</strong></td>"
            f"<td>{float(row['logfc']):.3f}</td>"
            f"<td>{float(row['pval_adj']):.2e}</td>"
            f"<td><code>{row['rna_gene']}</code></td>"
            f"{_r_cell(row['r'])}"
            f"</tr>"
        )

    return f"""
    <section>
      <h2>Cross-Modal Marker Table</h2>
      <p>
        Top ADT marker proteins per cell type (from DPE, cite_07), annotated
        with their RNA counterpart gene and Spearman correlation r (cite_09).
        Pairs with r &ge; 0.4 show strong RNA-protein coupling.
        Pairs with low r are post-transcriptionally regulated —
        the protein is a better cell-type marker than the mRNA.
      </p>
      <table>
        <thead>
          <tr>
            <th>Cell type</th>
            <th>Protein (ADT)</th>
            <th>log2FC</th>
            <th>adj p-value</th>
            <th>RNA gene</th>
            <th>Spearman r</th>
          </tr>
        </thead>
        <tbody>{trows}</tbody>
      </table>
    </section>"""


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def run_cite_epitope_report(
    mdata,
    epitope_dict: dict,
    report_path: str = "reports/cite_10_epitope_report.html",
    dataset_name: str = "dataset",
    corr_results: Optional[pd.DataFrame] = None,
) -> str:
    """
    Generate the CITE-seq epitope characterisation HTML report.

    Parameters
    ----------
    mdata : MuData
        MuData from cite_epitope (contains obs["epitope_score_*"]).
    epitope_dict : dict
        Dict returned by cite_epitope(). Keys: scores_df, panel_used,
        n_panels, marker_table, provenance.
    report_path : str
        Where to write the HTML file.
    dataset_name : str
        Dataset display name for the report header.
    corr_results : DataFrame or None
        Passed separately for the parallel violin plots (cite_09 results).

    Returns
    -------
    str
        Absolute path to the written HTML file.
    """
    out = Path(report_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    scores_df    = epitope_dict.get("scores_df", pd.DataFrame())
    panel_used   = epitope_dict.get("panel_used", {})
    marker_table = epitope_dict.get("marker_table", pd.DataFrame())
    provenance   = epitope_dict.get("provenance", {})
    group_col    = provenance.get("groupby", "adt_celltype_manual")

    print(f"Building CITE epitope report for '{dataset_name}' ...", flush=True)

    sections = [
        _section_run_summary(provenance, dataset_name, timestamp),
        _section_epitope_scores(mdata, scores_df, panel_used, group_col),
        _section_rna_protein_parallel(mdata, corr_results, group_col, n_pairs=6),
        _section_marker_table(marker_table),
    ]

    html = _render_page(sections, timestamp, dataset_name)
    out.write_text(html, encoding="utf-8")
    print(f"Report saved -> {out.resolve()}", flush=True)
    return str(out.resolve())
