"""
OmicSage — CITE-seq Protein-RNA Correlation Report
reports/templates/cite/cite_corr_report.py

Generated after cite_corr step (Step 9).
Output: cite_09_corr_report.html

Four sections
-------------
1. Run Summary  — matched/unmatched/tested/skipped counts, celltype_key used
2. Figures      — correlation distribution histogram + ranked bar chart
3. Results      — top 15 highest + bottom 15 lowest aggregate-r pairs
4. Per-Cell-Type Heatmap — proteins × cell types coloured by within-CT r
"""

from __future__ import annotations

import base64
import io
import json
from datetime import datetime
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

_DPI = 130

_CSS = """
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
           font-size: 14px; line-height: 1.6; color: #1a1a2e; background: #f7f8fc; }
    header { background: linear-gradient(135deg, #1a1a2e 0%, #16213e 60%, #0f3460 100%);
              color: white; padding: 32px 40px 24px; }
    header h1 { font-size: 1.8rem; font-weight: 700; }
    header p  { font-size: 0.85rem; opacity: 0.7; margin-top: 4px; }
    main { max-width: 1200px; margin: 0 auto; padding: 32px 24px; }
    section { background: white; border-radius: 10px;
               box-shadow: 0 1px 4px rgba(0,0,0,0.07);
               padding: 28px 32px; margin-bottom: 24px; }
    section h2 { font-size: 1.15rem; font-weight: 700; color: #0f3460;
                  border-bottom: 2px solid #e8eaf6;
                  padding-bottom: 10px; margin-bottom: 18px; }
    section h3 { font-size: 1rem; font-weight: 600; color: #16213e; margin: 16px 0 8px; }
    section p  { color: #444; margin-bottom: 12px; font-size: 0.9rem; }
    .timestamp { font-size: 0.8rem; color: #888; margin-bottom: 6px; }
    .note { font-size: 0.82rem; color: #7a5c00; background: #fffbe6;
             border-left: 3px solid #f0c040; padding: 8px 12px;
             border-radius: 4px; margin-bottom: 14px; }
    .interp { font-size: 0.82rem; color: #1e3a5f; background: #e8f0fe;
               border-left: 3px solid #4C78A8; padding: 8px 12px;
               border-radius: 4px; margin-bottom: 14px; }
    code { font-family: "SFMono-Regular", Consolas, monospace;
            background: #f0f2ff; padding: 1px 5px;
            border-radius: 3px; font-size: 0.85em; }
    .stat-grid { display: flex; flex-wrap: wrap; gap: 14px; margin-bottom: 24px; }
    .stat-card { background: #f0f2ff; border-radius: 8px; padding: 14px 20px;
                  min-width: 130px; text-align: center; flex: 1 1 130px; }
    .stat-value { font-size: 1.4rem; font-weight: 700; color: #0f3460; }
    .stat-label { font-size: 0.75rem; color: #666; margin-top: 2px; }
    table { width: 100%; border-collapse: collapse; font-size: 0.88rem; margin-top: 8px; }
    th { background: #f0f2ff; color: #0f3460; font-weight: 600;
          padding: 9px 12px; text-align: left; border-bottom: 2px solid #d0d4f0; }
    td { padding: 8px 12px; border-bottom: 1px solid #eee; vertical-align: middle; }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: #f8f9ff; }
    .fig-grid { display: flex; flex-wrap: wrap; gap: 18px; margin-top: 12px; }
    .fig-wrap { flex: 1 1 300px; max-width: 520px; }
    .fig-wrap.wide { flex: 1 1 100%; max-width: 100%; }
    .fig-wrap h3 { font-size: 0.9rem; margin-bottom: 6px; color: #16213e; }
    .fig-wrap img { width: 100%; border-radius: 6px; border: 1px solid #e8eaf6; }
    img { max-width: 100%; height: auto; }
    .r-high { color: #155724; font-weight: 600; }
    .r-low  { color: #856404; font-weight: 600; }
    .r-neg  { color: #721c24; font-weight: 600; }
    footer { text-align: center; font-size: 0.78rem; color: #aaa; padding: 24px 0 32px; }
    footer a { color: #0f3460; text-decoration: none; }
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _fig_to_b64(fig) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=_DPI, bbox_inches="tight")
    plt.close(fig)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("utf-8")


def _render_page(sections: list[str], timestamp: str, dataset_name: str) -> str:
    body = "\n".join(sections)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>OmicSage -- CITE-seq Protein-RNA Correlation -- {dataset_name}</title>
  <style>{_CSS}</style>
</head>
<body>
  <header>
    <h1>OmicSage -- CITE-seq Protein-RNA Correlation</h1>
    <p>Dataset: <strong>{dataset_name}</strong> &middot; Generated {timestamp}</p>
  </header>
  <main>{body}</main>
  <footer>Generated by <a href="https://github.com/fshokor/OmicSage">OmicSage</a>
  &middot; MIT License</footer>
</body>
</html>"""


def _r_class(r: float) -> str:
    if r >= 0.4:
        return "r-high"
    if r < 0:
        return "r-neg"
    return "r-low"


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------

def _plot_correlation_histogram(results_df: pd.DataFrame) -> str:
    """
    Distribution of aggregate Spearman r values across all matched pairs.
    Coloured by zone: high (green), moderate (yellow), low (orange), negative (red).
    """
    if results_df.empty:
        fig, ax = plt.subplots(figsize=(6, 3))
        ax.text(0.5, 0.5, "No correlation results to display.",
                ha="center", va="center", transform=ax.transAxes,
                fontsize=10, color="#888")
        ax.axis("off")
        return _fig_to_b64(fig)

    r_vals = results_df["r"].values
    fig, ax = plt.subplots(figsize=(7, 4))

    ax.axvspan(-1,  0.0, alpha=0.06, color="#c0392b", label="Negative")
    ax.axvspan( 0.0, 0.2, alpha=0.06, color="#e67e22", label="Low (0–0.2)")
    ax.axvspan( 0.2, 0.4, alpha=0.06, color="#f1c40f", label="Moderate (0.2–0.4)")
    ax.axvspan( 0.4, 1.0, alpha=0.08, color="#27ae60", label="High (>0.4)")

    ax.hist(r_vals, bins=20, color="#4C78A8", alpha=0.85, edgecolor="white",
            linewidth=0.5)
    ax.axvline(np.median(r_vals), color="#c0392b", linewidth=1.5,
               linestyle="--", label=f"Median r = {np.median(r_vals):.3f}")
    ax.axvline(0, color="#555", linewidth=0.8, linestyle=":")

    ax.set_xlabel("Aggregate Spearman r (Fisher-z weighted)", fontsize=10)
    ax.set_ylabel("Number of protein-gene pairs", fontsize=10)
    ax.set_title(
        "Distribution of Within-Cell-Type Protein-RNA Correlations\n"
        f"({len(r_vals)} matched pairs tested)",
        fontsize=11, fontweight="bold",
    )
    ax.legend(fontsize=8, frameon=False)
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    return _fig_to_b64(fig)


def _plot_ranked_correlations(results_df: pd.DataFrame) -> str:
    """Horizontal bar chart of all tested pairs ranked by aggregate r."""
    if results_df.empty:
        fig, ax = plt.subplots(figsize=(5, 2))
        ax.text(0.5, 0.5, "No correlation results to display.",
                ha="center", va="center", transform=ax.transAxes,
                fontsize=10, color="#888")
        ax.axis("off")
        return _fig_to_b64(fig)

    df = results_df.sort_values("r", ascending=True).reset_index(drop=True)
    labels = [f"{row['protein']} / {row['gene']}" for _, row in df.iterrows()]
    r_vals = df["r"].values

    colors = []
    for r in r_vals:
        if r >= 0.4:
            colors.append("#27ae60")
        elif r >= 0.2:
            colors.append("#f39c12")
        elif r >= 0:
            colors.append("#e67e22")
        else:
            colors.append("#c0392b")

    fig_height = max(5, len(labels) * 0.3)
    fig, ax = plt.subplots(figsize=(8, fig_height))
    ax.barh(labels, r_vals, color=colors, alpha=0.85, height=0.7)
    ax.axvline(0, color="#aaa", linewidth=0.8)
    ax.axvline(0.4, color="#27ae60", linewidth=0.8, linestyle="--",
               alpha=0.6, label="r = 0.4")
    ax.axvline(0.2, color="#f39c12", linewidth=0.8, linestyle="--",
               alpha=0.6, label="r = 0.2")

    ax.set_xlabel("Aggregate Spearman r", fontsize=10)
    ax.set_title(
        "All Protein-Gene Pairs Ranked by Aggregate r\n"
        "(protein / gene, sorted ascending)",
        fontsize=11, fontweight="bold",
    )
    ax.tick_params(axis="y", labelsize=7)
    ax.legend(fontsize=8, frameon=False, loc="lower right")
    ax.spines[["top", "right"]].set_visible(False)
    ax.set_xlim(-1, 1)
    fig.tight_layout()
    return _fig_to_b64(fig)


def _plot_per_celltype_heatmap(per_ct_df: pd.DataFrame) -> str:
    """
    Heatmap of within-cell-type Spearman r: proteins (rows) × cell types (cols).

    Each cell shows the r value for that protein-gene pair within that cell type.
    White = not tested (< min_cells_per_ct). Diverging colormap centred at 0.
    Positive r (green) = co-regulated within cell type.
    Negative r (red) = anti-correlated within cell type (true biology, not artifact).
    """
    if per_ct_df.empty:
        fig, ax = plt.subplots(figsize=(6, 3))
        ax.text(0.5, 0.5, "No per-cell-type results to display.",
                ha="center", va="center", transform=ax.transAxes,
                fontsize=10, color="#888")
        ax.axis("off")
        return _fig_to_b64(fig)

    # Pivot: protein as row index, cell_type as columns
    pivot = per_ct_df.pivot_table(
        index="protein", columns="cell_type", values="r", aggfunc="first"
    )

    # Sort rows by mean r descending so most-correlated proteins are at top
    pivot = pivot.loc[pivot.mean(axis=1).sort_values(ascending=False).index]

    n_proteins = len(pivot)
    n_celltypes = len(pivot.columns)
    fig_h = max(4, n_proteins * 0.35)
    fig_w = max(6, n_celltypes * 1.2)

    fig, ax = plt.subplots(figsize=(fig_w, fig_h))

    im = ax.imshow(
        pivot.values,
        cmap="RdYlGn",
        vmin=-1, vmax=1,
        aspect="auto",
        interpolation="nearest",
    )

    # Annotate cells with r values
    for i in range(n_proteins):
        for j in range(n_celltypes):
            val = pivot.values[i, j]
            if not np.isnan(val):
                text_color = "white" if abs(val) > 0.6 else "black"
                ax.text(j, i, f"{val:.2f}", ha="center", va="center",
                        fontsize=7, color=text_color)

    ax.set_xticks(range(n_celltypes))
    ax.set_xticklabels(pivot.columns, rotation=35, ha="right", fontsize=8)
    ax.set_yticks(range(n_proteins))
    ax.set_yticklabels(pivot.index, fontsize=8)
    ax.set_title(
        "Within-Cell-Type Protein-RNA Spearman r\n"
        "(white = not tested; green = co-regulated; red = anti-correlated)",
        fontsize=10, fontweight="bold",
    )

    cbar = fig.colorbar(im, ax=ax, fraction=0.03, pad=0.04)
    cbar.set_label("Spearman r", fontsize=9)
    cbar.ax.tick_params(labelsize=8)

    fig.tight_layout()
    return _fig_to_b64(fig)


# ---------------------------------------------------------------------------
# HTML sections
# ---------------------------------------------------------------------------

def _section_run_summary(
    provenance: dict,
    dataset_name: str,
    timestamp: str,
) -> str:
    n_panel        = provenance.get("n_proteins_panel", "?")
    n_matched      = provenance.get("n_matched", "?")
    n_unmatched    = provenance.get("n_unmatched", "?")
    n_tested       = provenance.get("n_tested", "?")
    n_skipped      = provenance.get("n_skipped", "?")
    method         = provenance.get("method", "spearman")
    min_cells      = provenance.get("min_cells", "?")
    min_cells_ct   = provenance.get("min_cells_per_ct", "?")
    bh_corr        = provenance.get("bh_correction", False)
    celltype_key   = provenance.get("celltype_key", "not reported")
    use_per_ct     = provenance.get("use_per_celltype", False)
    n_celltypes    = provenance.get("n_celltypes", 0)
    unmatched      = provenance.get("unmatched_proteins", [])

    unmatched_html = ""
    if unmatched:
        items = ", ".join(f"<code>{p}</code>" for p in unmatched[:20])
        more  = f" … and {len(unmatched) - 20} more" if len(unmatched) > 20 else ""
        unmatched_html = (
            f"<p class='note'>Proteins with no matching RNA gene symbol "
            f"({len(unmatched)} total): {items}{more}. "
            f"These are typically isotype controls or proteins whose antibody "
            f"name does not match the gene symbol convention.</p>"
        )

    mode_note = (
        f"Within-cell-type mode — r computed per cell type "
        f"(<code>{celltype_key}</code>, {n_celltypes} groups) "
        f"and aggregated using Fisher z-transform weighting. "
        f"This removes cross-population compositional artifacts from CLR normalization."
        if use_per_ct
        else
        "Global mode — r computed across all cells (no cell type column found). "
        "Results may reflect compositional artifacts. Run adt_annotate first for "
        "within-cell-type correlation."
    )
    mode_class = "interp" if use_per_ct else "note"

    cards = "".join(
        f'<div class="stat-card"><div class="stat-value">{v}</div>'
        f'<div class="stat-label">{k}</div></div>'
        for k, v in [
            ("Panel size",   n_panel),
            ("Matched",      n_matched),
            ("Unmatched",    n_unmatched),
            ("Tested",       n_tested),
            ("Skipped",      n_skipped),
        ]
    )
    rows = "".join(
        f"<tr><td>{k}</td><td><code>{v}</code></td></tr>"
        for k, v in [
            ("Method",              method),
            ("Min cells (global)",  min_cells),
            ("Min cells (per CT)",  min_cells_ct),
            ("Cell type key",       celltype_key),
            ("N cell types",        n_celltypes),
            ("BH FDR applied",      "yes" if bh_corr else "no (statsmodels not available)"),
        ]
    )
    return f"""
    <section>
      <h2>Run Summary</h2>
      <p class="timestamp">Dataset: <strong>{dataset_name}</strong>
         &middot; {timestamp}</p>
      <div class="interp">
        <strong>How to read this report:</strong>
        r values are computed <em>within each cell type</em> and aggregated
        using Fisher z-transform weighting. This removes the cross-cell-type
        compositional artifact that CLR normalization introduces in panels
        dominated by one lineage.
        High r (&gt; 0.4) = protein and mRNA co-regulated within cell type.
        Low or zero r (|r| &lt; 0.2) = post-transcriptional regulation.
        Negative r = true within-cell-type anti-correlation (rare; biologically meaningful).
      </div>
      <div class="{mode_class}">{mode_note}</div>
      {unmatched_html}
      <div class="stat-grid">{cards}</div>
      <table>
        <thead><tr><th>Parameter</th><th>Value</th></tr></thead>
        <tbody>{rows}</tbody>
      </table>
    </section>"""


def _section_figures(results_df: pd.DataFrame) -> str:
    if results_df.empty:
        return """
    <section>
      <h2>Figures</h2>
      <p class="note">No correlation results — no protein-gene pairs were matched
      or all pairs were below the min_cells threshold.</p>
    </section>"""

    print("  Rendering correlation histogram ...", flush=True)
    fig_hist   = _plot_correlation_histogram(results_df)
    print("  Rendering ranked correlation bar chart ...", flush=True)
    fig_ranked = _plot_ranked_correlations(results_df)

    return f"""
    <section>
      <h2>Figures</h2>
      <div class="fig-grid">
        <div class="fig-wrap">
          <h3>Correlation Distribution</h3>
          <img src="data:image/png;base64,{fig_hist}"
               alt="Spearman r distribution">
        </div>
        <div class="fig-wrap wide">
          <h3>All Matched Pairs Ranked by r</h3>
          <img src="data:image/png;base64,{fig_ranked}"
               alt="Ranked protein-gene correlations">
        </div>
      </div>
    </section>"""


def _section_per_celltype_heatmap(per_ct_df: pd.DataFrame) -> str:
    """New section: within-cell-type r heatmap (proteins × cell types)."""
    if per_ct_df.empty:
        return ""  # Section omitted entirely if no per-CT data

    print("  Rendering per-cell-type correlation heatmap ...", flush=True)
    fig_heatmap = _plot_per_celltype_heatmap(per_ct_df)

    return f"""
    <section>
      <h2>Within-Cell-Type Correlation Heatmap</h2>
      <p>
        Each cell shows the Spearman r between protein (ADT CLR) and mRNA
        expression computed within that cell type. White cells were not tested
        (too few cells expressing both modalities in that group).
        Green = protein and mRNA co-regulated within cell type.
        Red = anti-correlated within cell type.
      </p>
      <div class="interp">
        Proteins with consistently low or negative r across all cell types
        are post-transcriptionally regulated — the surface protein is a better
        cell-type marker than the mRNA. Proteins with high r only in specific
        cell types indicate context-dependent co-regulation.
      </div>
      <div class="fig-wrap wide">
        <img src="data:image/png;base64,{fig_heatmap}"
             alt="Per-cell-type protein-RNA correlation heatmap">
      </div>
    </section>"""


def _section_results_tables(results_df: pd.DataFrame) -> str:
    if results_df.empty:
        return """
    <section>
      <h2>Results</h2>
      <p class="note">No significant pairs to display.</p>
    </section>"""

    def _build_table(df: pd.DataFrame, title: str) -> str:
        if df.empty:
            return f"<h3>{title}</h3><p>None.</p>"
        rows = ""
        for _, row in df.iterrows():
            r_val = float(row["r"])
            css   = _r_class(r_val)
            sig = "✓" if float(row.get("pval_adj", 1.0)) < 0.05 and abs(r_val) >= 0.1 else ""
            n_ct  = int(row.get("n_celltypes", 0))
            n_ct_str = str(n_ct) if n_ct > 0 else "—"
            rows += (
                f"<tr>"
                f"<td><strong>{row['protein']}</strong></td>"
                f"<td>{row['gene']}</td>"
                f"<td class='{css}'>{r_val:.3f}</td>"
                f"<td>{float(row['pval']):.2e}</td>"
                f"<td>{float(row.get('pval_adj', float('nan'))):.2e}</td>"
                f"<td>{int(row['n_cells'])}</td>"
                f"<td style='text-align:center'>{n_ct_str}</td>"
                f"<td style='text-align:center'>{sig}</td>"
                f"<td><code>{row['matched_by']}</code></td>"
                f"</tr>"
            )
        header = (
            "<table>"
            "<thead><tr>"
            "<th>Protein</th><th>Gene</th><th>r</th>"
            "<th>p-value</th><th>adj p-value</th>"
            "<th>N cells</th><th>N cell types</th>"
            "<th>FDR &lt; 0.05</th><th>Match type</th>"
            "</tr></thead>"
            f"<tbody>{rows}</tbody></table>"
        )
        return f"<h3>{title}</h3>{header}"

    top_df = results_df.nlargest(15, "r")
    bot_df = results_df.nsmallest(15, "r")

    r_vals = results_df["r"].values
    n_high = int((r_vals >= 0.4).sum())
    n_mod  = int(((r_vals >= 0.2) & (r_vals < 0.4)).sum())
    n_low  = int(((r_vals >= 0) & (r_vals < 0.2)).sum())
    n_neg  = int((r_vals < 0).sum())
    n_sig  = int((results_df.get("pval_adj", results_df["pval"]) < 0.05).sum())

    summary_cards = "".join(
        f'<div class="stat-card"><div class="stat-value">{v}</div>'
        f'<div class="stat-label">{k}</div></div>'
        for k, v in [
            ("High r ≥ 0.4",     n_high),
            ("Moderate 0.2–0.4", n_mod),
            ("Low 0–0.2",        n_low),
            ("Negative r",       n_neg),
            ("FDR < 0.05",       n_sig),
            ("Median r",         f"{float(np.median(r_vals)):.3f}"),
        ]
    )

    return f"""
    <section>
      <h2>Results</h2>
      <div class="stat-grid">{summary_cards}</div>
      {_build_table(top_df, "Top 15 — Highest Correlation Pairs")}
      <div style="margin-top: 24px;">
        {_build_table(bot_df, "Bottom 15 — Lowest Correlation Pairs")}
      </div>
      <p style="margin-top:16px; font-size:0.85rem; color:#666;">
        Full results are stored in
        <code>mdata.uns["omicsage_cite_corr"]</code> and in the cite_09
        checkpoint file (<code>cite_09_corr.h5mu</code>).
      </p>
    </section>"""


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def run_cite_corr_report(
    corr_dict: dict,
    report_path: str = "reports/cite_09_corr_report.html",
    dataset_name: str = "dataset",
) -> str:
    """
    Generate the CITE-seq protein-RNA correlation HTML report.

    Parameters
    ----------
    corr_dict : dict
        Dict returned by cite_corr(). Keys: results, results_per_celltype,
        matched, unmatched, skipped, provenance.
    report_path : str
        Where to write the HTML file.
    dataset_name : str
        Dataset display name for the report header.

    Returns
    -------
    str
        Absolute path to the written HTML file.
    """
    out = Path(report_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    results_df = corr_dict.get("results", pd.DataFrame())
    per_ct_df  = corr_dict.get("results_per_celltype", pd.DataFrame())
    provenance = corr_dict.get("provenance", {})

    print(f"Building CITE correlation report for '{dataset_name}' ...", flush=True)

    sections = [
        _section_run_summary(provenance, dataset_name, timestamp),
        _section_figures(results_df),
        _section_per_celltype_heatmap(per_ct_df),
        _section_results_tables(results_df),
    ]

    html = _render_page(sections, timestamp, dataset_name)
    out.write_text(html, encoding="utf-8")
    print(f"Report saved -> {out.resolve()}", flush=True)
    return str(out.resolve())
