"""
OmicSage — CITE-seq GSEA Report
reports/templates/cite/cite_gsea_report.py

Generated after cite_gsea step (Step 8).
Output: cite_08_gsea_report.html

Shows ORA pathway enrichment results derived from cross-modal RNA DEG
gene lists (ADT-defined cell types → RNA transcriptional programs).
"""

from __future__ import annotations

import base64
import io
from datetime import datetime
from pathlib import Path
from typing import Optional

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

_DPI = 130

_CSS = """
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
           font-size: 14px; line-height: 1.6; color: #1a1a2e; background: #f7f8fc; }
    header { background: linear-gradient(135deg, #1a1a2e 0%, #16213e 60%, #0f3460 100%);
              color: white; padding: 32px 40px 24px; }
    header h1 { font-size: 1.8rem; font-weight: 700; }
    header p  { font-size: 0.85rem; opacity: 0.7; margin-top: 4px; }
    main { max-width: 1200px; margin: 0 auto; padding: 32px 24px; }
    section { background: white; border-radius: 10px;
               box-shadow: 0 1px 4px rgba(0,0,0,0.07);
               padding: 28px 32px; margin-bottom: 24px; }
    section h2 { font-size: 1.15rem; font-weight: 700; color: #0f3460;
                  border-bottom: 2px solid #e8eaf6;
                  padding-bottom: 10px; margin-bottom: 18px; }
    section h3 { font-size: 1rem; font-weight: 600; color: #16213e;
                  margin: 16px 0 8px; }
    section p  { color: #444; margin-bottom: 12px; font-size: 0.9rem; }
    .timestamp { font-size: 0.8rem; color: #888; margin-bottom: 6px; }
    .note { font-size: 0.82rem; color: #7a5c00; background: #fffbe6;
             border-left: 3px solid #f0c040; padding: 8px 12px;
             border-radius: 4px; margin-bottom: 14px; }
    code { font-family: "SFMono-Regular", Consolas, monospace;
            background: #f0f2ff; padding: 1px 5px;
            border-radius: 3px; font-size: 0.85em; }
    .stat-grid { display: flex; flex-wrap: wrap; gap: 14px; margin-bottom: 24px; }
    .stat-card { background: #f0f2ff; border-radius: 8px; padding: 14px 20px;
                  min-width: 130px; text-align: center; flex: 1 1 130px; }
    .stat-value { font-size: 1.4rem; font-weight: 700; color: #0f3460; }
    .stat-label { font-size: 0.75rem; color: #666; margin-top: 2px; }
    table { width: 100%; border-collapse: collapse;
             font-size: 0.88rem; margin-top: 8px; }
    th { background: #f0f2ff; color: #0f3460; font-weight: 600;
          padding: 9px 12px; text-align: left; border-bottom: 2px solid #d0d4f0; }
    td { padding: 8px 12px; border-bottom: 1px solid #eee;
          vertical-align: middle; }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: #f8f9ff; }
    .fig-grid { display: flex; flex-wrap: wrap; gap: 18px; margin-top: 12px; }
    .fig-wrap { flex: 1 1 300px; max-width: 520px; }
    .fig-wrap.wide { flex: 1 1 100%; max-width: 100%; }
    .fig-wrap h3 { font-size: 0.9rem; margin-bottom: 6px; color: #16213e; }
    .fig-wrap img { width: 100%; border-radius: 6px; border: 1px solid #e8eaf6; }
    img { max-width: 100%; height: auto; }
    .db-tag { display:inline-block; padding:2px 8px; border-radius:20px;
               font-size:0.75rem; font-weight:600; margin-right:4px; }
    .db-go       { background:#dbeafe; color:#1e40af; }
    .db-kegg     { background:#d1fae5; color:#065f46; }
    .db-reactome { background:#fce7f3; color:#831843; }
    .db-other    { background:#f3f4f6; color:#374151; }
    footer { text-align: center; font-size: 0.78rem; color: #aaa;
              padding: 24px 0 32px; }
    footer a { color: #0f3460; text-decoration: none; }
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _fig_to_b64(fig) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=_DPI, bbox_inches="tight")
    plt.close(fig)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("utf-8")


def _render_page(sections: list[str], timestamp: str, dataset_name: str) -> str:
    body = "\n".join(sections)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>OmicSage -- CITE-seq GSEA Report -- {dataset_name}</title>
  <style>{_CSS}</style>
</head>
<body>
  <header>
    <h1>OmicSage -- CITE-seq GSEA Report</h1>
    <p>Dataset: <strong>{dataset_name}</strong> &middot; Generated {timestamp}</p>
  </header>
  <main>{body}</main>
  <footer>Generated by <a href="https://github.com/fshokor/OmicSage">OmicSage</a>
  &middot; MIT License</footer>
</body>
</html>"""


def _db_tag(gene_set: str) -> str:
    """Return a coloured badge for a gene set library name."""
    gs = gene_set.lower()
    if "go" in gs or "biological_process" in gs:
        return f'<span class="db-tag db-go">GO BP</span>'
    if "kegg" in gs:
        return f'<span class="db-tag db-kegg">KEGG</span>'
    if "reactome" in gs:
        return f'<span class="db-tag db-reactome">Reactome</span>'
    return f'<span class="db-tag db-other">{gene_set[:12]}</span>'


# Translation / ribosome pathway keywords — these dominate when RPL*/RPS*
# genes are not excluded from DEG input before GSEA
_TRANSLATION_KEYWORDS = {
    "translation elongation", "translation initiation", "peptide chain elongation",
    "cytoplasmic translation", "ribosom", "cotranslational",
    "srp-dependent", "cap-dependent translation",
}

# KEGG disease pathways that frequently appear as false positives in immune cells
# because they contain MHC / cytokine genes shared with normal immune function
_KEGG_DISEASE_KEYWORDS = {
    "asthma", "lupus", "rheumatoid arthritis", "type i diabetes",
    "graft-versus-host", "allograft rejection", "inflammatory bowel",
    "malaria",  # appears due to haemoglobin / RBC metabolism genes
}


def _check_gsea_flags(
    results: dict[str, pd.DataFrame],
    summary_df: pd.DataFrame,
) -> str:
    """
    Detect two common GSEA artifact classes and return an HTML warning block.

    1. Translation pathway dominance: top pathway is ribosomal/translation for
       ≥ 2 cell types — indicates RPL*/RPS* genes were not excluded from DEG input.
    2. KEGG disease pathway for immune cell types: spurious hits due to shared
       MHC/cytokine gene content between disease and normal immune pathways.
    """
    if not results:
        return ""

    _P_COL = next(
        (c for c in ["Adjusted P-value", "Adjusted P-Value", "FDR q-val", "adj_pval"]
         if any(c in df.columns for df in results.values() if not df.empty)),
        None,
    )
    _T_COL = next(
        (c for c in ["Term", "term", "pathway", "Description"]
         if any(c in df.columns for df in results.values() if not df.empty)),
        None,
    )

    if _P_COL is None or _T_COL is None:
        return ""

    translation_cts: list[str] = []
    disease_flags:   list[tuple[str, str]] = []

    for ct, df in results.items():
        if df.empty:
            continue
        top1 = df.nsmallest(1, _P_COL)
        if top1.empty:
            continue
        top_term = str(top1.iloc[0][_T_COL]).lower()

        # Translation dominance check
        if any(kw in top_term for kw in _TRANSLATION_KEYWORDS):
            translation_cts.append(ct)

        # KEGG disease pathway check — scan top 5
        top5_terms = df.nsmallest(5, _P_COL)[_T_COL].astype(str).str.lower().tolist()
        for term in top5_terms:
            if any(kw in term for kw in _KEGG_DISEASE_KEYWORDS):
                disease_flags.append((ct, term))

    flags_html = ""

    if len(translation_cts) >= 2:
        cts = ", ".join(f"<strong>{c}</strong>" for c in translation_cts)
        flags_html += (
            f"<div class='note'>"
            f"<strong>⚠ Translation pathway dominance detected</strong> in: {cts}. "
            f"When ribosomal protein genes (<code>RPL*</code> / <code>RPS*</code>) "
            f"are the top DEGs, translation pathways dominate GSEA results and mask "
            f"genuine biology. This is a compositional artefact — these genes are "
            f"highly expressed in most cells and top the one-vs-rest DEG list by "
            f"default. <strong>Recommended fix:</strong> add "
            f"<code>exclude_gene_prefixes: [RPL, RPS]</code> to the cite_deg config "
            f"and re-run cite_07 and cite_08."
            f"</div>"
        )

    if disease_flags:
        items = "".join(
            f"<li><strong>{ct}</strong>: <em>{term}</em></li>"
            for ct, term in disease_flags
        )
        flags_html += (
            f"<div class='note'>"
            f"<strong>⚠ KEGG disease pathway(s) in top 5 for immune cell types:</strong>"
            f"<ul style='margin:6px 0 0 16px;'>{items}</ul>"
            f"These KEGG disease pathways contain MHC, cytokine, or metabolic genes "
            f"shared with normal immune cell biology. The enrichment reflects gene "
            f"content overlap, not disease association. Cross-check with GO BP or "
            f"Reactome results to identify the genuine underlying biology."
            f"</div>"
        )

    return flags_html


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------

def _plot_top_pathways_bar(
    results: dict[str, pd.DataFrame],
    n_top: int = 10,
) -> str:
    """
    Horizontal bar chart: top n_top pathways per cell type, coloured by
    -log10(adjusted p-value). One panel per cell type.
    """
    # Determine the adjusted p-value column name (varies by gseapy version)
    _P_COL = None
    for candidate in ["Adjusted P-value", "Adjusted P-Value", "FDR q-val", "adj_pval"]:
        for df in results.values():
            if not df.empty and candidate in df.columns:
                _P_COL = candidate
                break
        if _P_COL:
            break

    # Term column
    _T_COL = None
    for candidate in ["Term", "term", "pathway", "Description"]:
        for df in results.values():
            if not df.empty and candidate in df.columns:
                _T_COL = candidate
                break
        if _T_COL:
            break

    cell_types = [ct for ct, df in results.items() if not df.empty]
    if not cell_types or _P_COL is None or _T_COL is None:
        fig, ax = plt.subplots(figsize=(5, 2))
        ax.text(0.5, 0.5, "No significant pathways to display.",
                ha="center", va="center", transform=ax.transAxes,
                fontsize=10, color="#888")
        ax.axis("off")
        return _fig_to_b64(fig)

    n_cols = min(2, len(cell_types))
    n_rows = (len(cell_types) + n_cols - 1) // n_cols
    fig, axes = plt.subplots(n_rows, n_cols,
                              figsize=(n_cols * 6.5, n_rows * 4))
    axes = np.array(axes).flatten()

    for i, ct in enumerate(cell_types):
        ax = axes[i]
        df = results[ct].copy()

        if df.empty or _P_COL not in df.columns:
            ax.axis("off")
            continue

        df = df[df[_P_COL] < 1.0].nsmallest(n_top, _P_COL)
        if df.empty:
            ax.axis("off")
            continue

        # Shorten long pathway names
        terms = df[_T_COL].astype(str).apply(
            lambda t: t[:55] + "…" if len(t) > 55 else t
        ).tolist()
        neg_log_p = -np.log10(df[_P_COL].clip(lower=1e-300).values)

        # Colour by database if Gene_set column present
        if "Gene_set" in df.columns:
            gene_sets = df["Gene_set"].astype(str).tolist()
            palette = {
                "GO": "#4C78A8",
                "KEGG": "#54a868",
                "Reactome": "#e07b3a",
            }
            bar_colors = []
            for gs in gene_sets:
                if "GO" in gs or "Biological" in gs:
                    bar_colors.append(palette["GO"])
                elif "KEGG" in gs:
                    bar_colors.append(palette["KEGG"])
                elif "Reactome" in gs:
                    bar_colors.append(palette["Reactome"])
                else:
                    bar_colors.append("#9467bd")
        else:
            bar_colors = ["#4C78A8"] * len(terms)

        ax.barh(terms[::-1], neg_log_p[::-1],
                color=bar_colors[::-1], alpha=0.85, height=0.65)
        ax.axvline(
            -np.log10(0.05), color="#c0392b",
            linewidth=1, linestyle="--", alpha=0.7,
            label="adj p = 0.05",
        )
        ax.set_title(ct, fontsize=9, fontweight="bold")
        ax.set_xlabel("−log₁₀(adj p-value)", fontsize=8)
        ax.tick_params(axis="y", labelsize=6.5)
        ax.tick_params(axis="x", labelsize=7)
        ax.spines[["top", "right"]].set_visible(False)
        if i == 0:
            ax.legend(fontsize=7, frameon=False)

    for j in range(len(cell_types), len(axes)):
        axes[j].axis("off")

    fig.suptitle(
        f"Top {n_top} Pathways per Cell Type  (−log₁₀ adjusted p-value)",
        fontsize=12, fontweight="bold", y=1.01,
    )
    fig.tight_layout()
    return _fig_to_b64(fig)


def _plot_pathway_heatmap(
    results: dict[str, pd.DataFrame],
    n_top: int = 5,
) -> str:
    """
    Heatmap: rows = top pathways (union across cell types),
    columns = cell types, values = -log10(adj p-value).
    Shows the shared pathway landscape across all populations.
    """
    _P_COL = None
    _T_COL = None
    for candidate_p in ["Adjusted P-value", "Adjusted P-Value", "FDR q-val"]:
        for candidate_t in ["Term", "term", "pathway"]:
            for df in results.values():
                if (not df.empty
                        and candidate_p in df.columns
                        and candidate_t in df.columns):
                    _P_COL = candidate_p
                    _T_COL = candidate_t
                    break
            if _P_COL:
                break
        if _P_COL:
            break

    if _P_COL is None or _T_COL is None:
        fig, ax = plt.subplots(figsize=(4, 2))
        ax.text(0.5, 0.5, "Pathway heatmap: required columns not found.",
                ha="center", va="center", transform=ax.transAxes,
                fontsize=9, color="#888")
        ax.axis("off")
        return _fig_to_b64(fig)

    # Collect top n_top pathways per cell type
    top_terms: list[str] = []
    for ct, df in results.items():
        if df.empty:
            continue
        terms = df.nsmallest(n_top, _P_COL)[_T_COL].tolist()
        top_terms.extend(terms)

    # Deduplicate preserving order
    seen: set[str] = set()
    unique_terms: list[str] = []
    for t in top_terms:
        if t not in seen:
            seen.add(t)
            unique_terms.append(t)

    if not unique_terms:
        fig, ax = plt.subplots(figsize=(4, 2))
        ax.text(0.5, 0.5, "No pathways to show in heatmap.",
                ha="center", va="center", transform=ax.transAxes,
                fontsize=9, color="#888")
        ax.axis("off")
        return _fig_to_b64(fig)

    cell_types = list(results.keys())

    # Build matrix
    matrix = np.zeros((len(unique_terms), len(cell_types)))
    for j, ct in enumerate(cell_types):
        df = results[ct]
        if df.empty or _T_COL not in df.columns:
            continue
        term_to_p = dict(zip(df[_T_COL], df[_P_COL]))
        for i, term in enumerate(unique_terms):
            p = term_to_p.get(term, 1.0)
            matrix[i, j] = -np.log10(max(p, 1e-300))

    # Shorten labels
    ylabels = [t[:60] + "…" if len(t) > 60 else t for t in unique_terms]

    fig_h = max(5, len(unique_terms) * 0.35)
    fig_w = max(6, len(cell_types) * 1.2)
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))

    im = ax.imshow(matrix, aspect="auto", cmap="YlOrRd",
                   vmin=0, vmax=max(matrix.max(), 1))
    plt.colorbar(im, ax=ax, fraction=0.03, pad=0.02,
                 label="−log₁₀(adj p-value)")

    ax.set_xticks(range(len(cell_types)))
    ax.set_xticklabels(cell_types, rotation=30, ha="right", fontsize=9)
    ax.set_yticks(range(len(unique_terms)))
    ax.set_yticklabels(ylabels, fontsize=7)
    ax.set_title(
        f"Pathway Enrichment Heatmap\n"
        f"(top {n_top} pathways per cell type, union shown)",
        fontsize=11, fontweight="bold",
    )
    fig.tight_layout()
    return _fig_to_b64(fig)


# ---------------------------------------------------------------------------
# HTML sections
# ---------------------------------------------------------------------------

def _section_run_summary(
    provenance: dict,
    dataset_name: str,
    timestamp: str,
) -> str:
    n_tested  = provenance.get("n_groups_tested", "?")
    n_skipped = provenance.get("n_groups_skipped", "?")
    gene_sets = provenance.get("gene_sets") or ["GO_Biological_Process_2023",
                                                 "KEGG_2021_Human",
                                                 "Reactome_2022"]
    direction  = provenance.get("direction", "up")
    organism   = provenance.get("organism", "human")
    note_str   = provenance.get("note", "")
    skipped    = provenance.get("groups_skipped", [])

    db_badges = " ".join(_db_tag(gs) for gs in gene_sets)

    skipped_html = ""
    if skipped:
        skip_items = "".join(
            f"<li><code>{g}</code> ({d})</li>" for g, d in skipped
        )
        skipped_html = (
            f"<p class='note'>Groups skipped (fewer than min_genes DEGs): "
            f"<ul>{skip_items}</ul></p>"
        )

    cards = "".join(
        f'<div class="stat-card"><div class="stat-value">{v}</div>'
        f'<div class="stat-label">{k}</div></div>'
        for k, v in [
            ("Groups tested",  n_tested),
            ("Groups skipped", n_skipped),
            ("Direction",      direction),
            ("Organism",       organism),
        ]
    )
    rows = "".join(
        f"<tr><td>{k}</td><td>{v}</td></tr>"
        for k, v in [
            ("Gene set libraries", db_badges),
            ("Min log2FC",         provenance.get("min_logfc", "?")),
            ("Max adj p-value",    provenance.get("max_pval_adj", "?")),
            ("Source DEG module",  provenance.get("source_deg_module", "cite_deg")),
        ]
    )
    return f"""
    <section>
      <h2>Run Summary</h2>
      <p class="timestamp">Dataset: <strong>{dataset_name}</strong>
         &middot; {timestamp}</p>
      <p style="color:#444;font-size:0.88rem;">{note_str}</p>
      {skipped_html}
      <div class="stat-grid">{cards}</div>
      <table>
        <thead><tr><th>Parameter</th><th>Value</th></tr></thead>
        <tbody>{rows}</tbody>
      </table>
    </section>"""


def _section_pathway_figures(results: dict[str, pd.DataFrame]) -> str:
    if not results:
        return """
    <section>
      <h2>Figures</h2>
      <p class="note">No enrichment results to plot — all groups were skipped
      or had no significant pathways.</p>
    </section>"""

    print("  Rendering GSEA bar charts ...", flush=True)
    fig_bars = _plot_top_pathways_bar(results, n_top=10)
    print("  Rendering pathway heatmap ...", flush=True)
    fig_heatmap = _plot_pathway_heatmap(results, n_top=5)

    return f"""
    <section>
      <h2>Figures</h2>
      <h3>Top 10 Pathways per Cell Type</h3>
      <p>
        Horizontal bars show −log₁₀(adjusted p-value). Dashed red line marks
        adj p = 0.05. Colour indicates database:
        <span class="db-tag db-go">GO BP</span>
        <span class="db-tag db-kegg">KEGG</span>
        <span class="db-tag db-reactome">Reactome</span>.
      </p>
      <div class="fig-grid">
        <div class="fig-wrap wide">
          <img src="data:image/png;base64,{fig_bars}"
               alt="Top pathways per cell type">
        </div>
      </div>
      <h3>Pathway Enrichment Heatmap</h3>
      <p>Union of top 5 pathways per cell type. Colour intensity =
      −log₁₀(adj p-value). Grey cells = pathway not significant in that group.</p>
      <div class="fig-grid">
        <div class="fig-wrap wide">
          <img src="data:image/png;base64,{fig_heatmap}"
               alt="Pathway heatmap across cell types">
        </div>
      </div>
    </section>"""


def _section_pathway_table(
    results: dict[str, pd.DataFrame],
    summary_df: pd.DataFrame,
) -> str:
    """Top 3 pathways per cell type in a compact summary table + artifact flags."""
    gsea_flags_html = _check_gsea_flags(results, summary_df)

    if not results or summary_df.empty:
        # Try to build summary from raw results
        rows_html = "<p>No significant pathways found.</p>"
    else:
        # Detect column names
        _P_COL = next(
            (c for c in ["Adjusted P-value", "Adjusted P-Value", "FDR q-val"]
             if c in summary_df.columns), None
        )
        _T_COL = next(
            (c for c in ["Term", "term", "pathway"]
             if c in summary_df.columns), None
        )
        _GS_COL = next(
            (c for c in ["Gene_set", "Gene Set"]
             if c in summary_df.columns), None
        )

        if _T_COL is None or _P_COL is None:
            rows_html = "<p>Summary table columns not in expected format.</p>"
        else:
            trows = ""
            for _, row in summary_df.iterrows():
                term = str(row[_T_COL])
                term_short = term[:80] + "…" if len(term) > 80 else term
                pval = float(row[_P_COL]) if _P_COL else 1.0
                gs_badge = _db_tag(str(row[_GS_COL])) if _GS_COL else ""
                group = row.get("Group", row.get("group", ""))
                trows += (
                    f"<tr>"
                    f"<td>{group}</td>"
                    f"<td>{gs_badge} {term_short}</td>"
                    f"<td>{pval:.2e}</td>"
                    f"</tr>"
                )
            rows_html = f"""
            <table>
              <thead>
                <tr>
                  <th>Cell type</th>
                  <th>Top pathway</th>
                  <th>adj p-value</th>
                </tr>
              </thead>
              <tbody>{trows}</tbody>
            </table>"""

    return f"""
    <section>
      <h2>Top Pathways per Cell Type</h2>
      <p>
        Top 3 enriched pathways per ADT-defined cell type across all queried
        gene set libraries. Full results are stored in
        <code>uns["omicsage_cite_gsea"]</code>.
      </p>
      {gsea_flags_html}
      {rows_html}
    </section>"""


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def run_cite_gsea_report(
    gsea_dict: dict,
    report_path: str = "reports/cite_08_gsea_report.html",
    dataset_name: str = "dataset",
) -> str:
    """
    Generate the CITE-seq GSEA HTML report.

    Parameters
    ----------
    gsea_dict : dict
        Dict returned by cite_gsea(). Keys: results, summary_df,
        provenance, skipped.
    report_path : str
        Where to write the HTML file.
    dataset_name : str
        Dataset display name for the report header.

    Returns
    -------
    str
        Absolute path to the written HTML file.
    """
    out = Path(report_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    results    = gsea_dict.get("results", {})
    summary_df = gsea_dict.get("summary_df", pd.DataFrame())
    provenance = gsea_dict.get("provenance", {})

    print(f"Building CITE GSEA report for '{dataset_name}' ...", flush=True)

    sections = [
        _section_run_summary(provenance, dataset_name, timestamp),
        _section_pathway_figures(results),
        _section_pathway_table(results, summary_df),
    ]

    html = _render_page(sections, timestamp, dataset_name)
    out.write_text(html, encoding="utf-8")
    print(f"Report saved -> {out.resolve()}", flush=True)
    return str(out.resolve())
